//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.DomainEntities.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> FacultyID { get; set; }
    
        public virtual Students Students1 { get; set; }
        public virtual Students Students2 { get; set; }
    }
}
